"""upgrade_profiles_and_teams

Revision ID: 0e365308e76a
Revises: adf45f956f68
Create Date: 2026-09-30 18:08:29.221602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e365308e76a'
down_revision: Union[str, Sequence[str], None] = 'adf45f956f68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('join_requests', sa.Column('role', sa.String(), nullable=True))
    op.add_column('join_requests', sa.Column('technologies', sa.String(), nullable=True))
    op.add_column('join_requests', sa.Column('experience_summary', sa.Text(), nullable=True))
    op.add_column('join_requests', sa.Column('relevant_projects', sa.Text(), nullable=True))
    op.add_column('join_requests', sa.Column('github', sa.String(), nullable=True))
    op.add_column('join_requests', sa.Column('portfolio', sa.String(), nullable=True))
    op.add_column('join_requests', sa.Column('why_join', sa.Text(), nullable=True))
    op.add_column('join_requests', sa.Column('contribution', sa.Text(), nullable=True))
    op.add_column('notifications', sa.Column('link', sa.String(), nullable=True))
    op.add_column('student_profiles', sa.Column('avatar', sa.String(), nullable=True))
    op.add_column('student_profiles', sa.Column('languages', sa.String(), nullable=True))
    op.add_column('student_profiles', sa.Column('frameworks', sa.String(), nullable=True))
    op.add_column('student_profiles', sa.Column('tools', sa.String(), nullable=True))
    op.add_column('student_profiles', sa.Column('skills_proficiency', sa.Text(), nullable=True))
    op.add_column('student_profiles', sa.Column('certifications', sa.Text(), nullable=True))
    op.add_column('student_profiles', sa.Column('courses', sa.Text(), nullable=True))
    op.add_column('student_profiles', sa.Column('hackathons_history', sa.Text(), nullable=True))
    op.add_column('student_profiles', sa.Column('projects_list', sa.Text(), nullable=True))
    op.add_column('student_profiles', sa.Column('achievements', sa.Text(), nullable=True))
    op.add_column('student_profiles', sa.Column('working_style', sa.String(), nullable=True))
    op.add_column('student_profiles', sa.Column('communication_pref', sa.String(), nullable=True))
    op.add_column('student_profiles', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('student_profiles', sa.Column('show_phone', sa.Boolean(), nullable=True))
    op.add_column('teams', sa.Column('looking_for_roles', sa.String(), nullable=True))
    op.add_column('teams', sa.Column('required_skills', sa.String(), nullable=True))
    op.add_column('teams', sa.Column('availability_requirements', sa.String(), nullable=True))
    op.add_column('users', sa.Column('avatar', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar')
    op.drop_column('teams', 'availability_requirements')
    op.drop_column('teams', 'required_skills')
    op.drop_column('teams', 'looking_for_roles')
    op.drop_column('student_profiles', 'show_phone')
    op.drop_column('student_profiles', 'phone')
    op.drop_column('student_profiles', 'communication_pref')
    op.drop_column('student_profiles', 'working_style')
    op.drop_column('student_profiles', 'achievements')
    op.drop_column('student_profiles', 'projects_list')
    op.drop_column('student_profiles', 'hackathons_history')
    op.drop_column('student_profiles', 'courses')
    op.drop_column('student_profiles', 'certifications')
    op.drop_column('student_profiles', 'skills_proficiency')
    op.drop_column('student_profiles', 'tools')
    op.drop_column('student_profiles', 'frameworks')
    op.drop_column('student_profiles', 'languages')
    op.drop_column('student_profiles', 'avatar')
    op.drop_column('notifications', 'link')
    op.drop_column('join_requests', 'contribution')
    op.drop_column('join_requests', 'why_join')
    op.drop_column('join_requests', 'portfolio')
    op.drop_column('join_requests', 'github')
    op.drop_column('join_requests', 'relevant_projects')
    op.drop_column('join_requests', 'experience_summary')
    op.drop_column('join_requests', 'technologies')
    op.drop_column('join_requests', 'role')
    # ### end Alembic commands ###
