"""add profile fields

Revision ID: adf45f956f68
Revises: 42e3a708a7f7
Create Date: 2026-09-30 16:42:23.325907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adf45f956f68'
down_revision: Union[str, Sequence[str], None] = '42e3a708a7f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profiles', sa.Column('leetcode_link', sa.String(), nullable=True))
    op.add_column('student_profiles', sa.Column('experience', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_profiles', 'experience')
    op.drop_column('student_profiles', 'leetcode_link')
    # ### end Alembic commands ###
